name: Scheduled ETL

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run ETL script
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: python backend/scripts/sync_all.py
